# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'

User.destroy_all
Restaurant.destroy_all
Menu.destroy_all
Review.destroy_all
Favorite.destroy_all


User.create!(email: "user1@ht.com", first_name: "Pablo", last_name: "Escobar", primary_location: "Queens", password: "fireball42")
User.create!(email: "user2@ht.com", first_name: Faker::Name.first_name , last_name: Faker::Name.last_name , primary_location: "Brooklyn", password: "fireball42")
User.create!(email: "user3@ht.com", first_name: Faker::Name.first_name , last_name: Faker::Name.last_name , primary_location: "Manhattan", password: "fireball42")
User.create!(email: "user4@ht.com", first_name: Faker::Name.first_name , last_name: Faker::Name.last_name , primary_location: "Bronx", password: "fireball42")
User.create!(email: "user5@ht.com", first_name: Faker::Name.first_name , last_name: Faker::Name.last_name , primary_location: "Staten Island", password: "fireball42")
User.create!(email: "user6@ht.com", first_name: Faker::Name.first_name , last_name: Faker::Name.last_name , primary_location: "Queens", password: "fireball42")
User.create!(email: "demo@ht.com", first_name: "Demo" , last_name: "User" , primary_location: "Queens", password: "fireball42")

Restaurant.create!(name: "Addy’s Barbeque", phone_number: "(718) 433-9568", street_address: "30-94 Steinway St", city: "Queens", state: "NY", zip: "11103", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:00", price_range: "$$", capacity: 30, cuisines: "Barbeque", owner_id: 1, ratings: 5, lat: 40.756630, lng: -73.922160)

file = open('https://s3.amazonaws.com/halaltable-seeds/1.jpg')
Restaurant.last.main_photo.attach(io: file, filename: "1.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy3.jpg"), filename: "addy3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy4.jpg"), filename: "addy4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy5.jpg"), filename: "addy5.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy6.jpg"), filename: "addy6.jpg")

Restaurant.create!(name: "Shawarmania", phone_number: "(718) 545-1800", street_address: "22-49 31st St", city: "Queens", state: "NY", zip: "11105", description: Faker::Restaurant.description, open_time: "11:00", close_time: "22:00", price_range: "$$", capacity: 20, cuisines: "Middle Eastern", owner_id: 2, ratings: 5, lat: 51.702350 , lng: 4.846990)
file = open('https://s3.amazonaws.com/halaltable-seeds/2.jpg')
Restaurant.last.main_photo.attach(io: file, filename: "2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma1.jpg"), filename: "shawarma1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma2.jpg"), filename: "shawarma2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma3.jpeg"), filename: "shawarma3.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma4.jpg"), filename: "shawarma4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma5.jpeg"), filename: "shawarma5.jpeg")

Restaurant.create!(name: "AwesomeSauce", phone_number: "(718) 204-0275", street_address: "40-06 Queens Blvd S", city: "Queens", state: "NY", zip: "11103", description: Faker::Restaurant.description, open_time: "12:00", close_time: "00:00", price_range: "$$", capacity: 22, cuisines: "Burgers & Wings", owner_id: 1, ratings: 5, lat: 40.718980, lng: -73.880980)
file = open('https://s3.amazonaws.com/halaltable-seeds/3.jpg')
Restaurant.last.main_photo.attach(io: file, filename: "3.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as1.jpg"), filename: "as1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as2.jpg"), filename: "as2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as3.jpg"), filename: "as3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as4.jpg"), filename: "as4.jpg")


Restaurant.create!(name: "Duzan", phone_number: "(718) 204-7488", street_address: "2411 Steinway St", city: "Queens", state: "NY", zip: "11103", description: Faker::Restaurant.description, open_time: "12:00", close_time: "00:00", price_range: "$$", capacity: 15, cuisines: "Middle Eastern", owner_id: 4, ratings: 5, lat: 40.768669, lng: -73.910881)
file = open('https://s3.amazonaws.com/halaltable-seeds/4.jpg')
Restaurant.last.main_photo.attach(io: file, filename: "4.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan1.jpg"), filename: "duzan1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan2.jpg"), filename: "duzan2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan3.jpg"), filename: "duzan3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan4.jpg"), filename: "duzan4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan5.png"), filename: "duzan5.png")

Restaurant.create!(name: "Sami's Kabab House", phone_number: "(917) 832-7165", street_address: "35-57 Crescent St", city: "Queens", state: "NY", zip: "11106", description: Faker::Restaurant.description, open_time: "11:00", close_time: "23:30", price_range: "$$$", capacity: 15, cuisines: "Afgan", owner_id: 5, ratings: 5, lat: 40.768669, lng: -73.912881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/blur-close-up-cutlery-dining-370984.jpg"), filename: "4.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami1.jpg"), filename: "sami1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami2.jpeg"), filename: "sami2.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami3.jpg"), filename: "sami3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami4.jpg"), filename: "sami4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami5.jpg"), filename: "sami5.jpg")


Restaurant.create!(name: "Peri Peri Grill House", phone_number: "(917) 966-8614", street_address: "235 Malcolm X Blvd", city: "Brooklyn", state: "NY", zip: "11233", description: Faker::Restaurant.description, open_time: "12:00", close_time: "00:00", price_range: "$$", capacity: 25, cuisines: "Middle Eastern", owner_id: 1, ratings: 5, lat: 40.650002, lng: -73.949997)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/chair-cutlery-diner-dining-941861.jpg"), filename: "5.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri1.jpeg"), filename: "peri1.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri2.jpg"), filename: "peri2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri3.jpg"), filename: "peri3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri4.jpg"), filename: "peri4.jpg")

Restaurant.create!(name: "Taci's Beyti", phone_number: "(718) 627-5750", street_address: "1953 Coney Island Ave", city: "Brooklyn", state: "NY", zip: "11223", description: Faker::Restaurant.description, open_time: "12:00", close_time: "23:00", price_range: "$$", capacity: 25, cuisines: "Turkish", owner_id: 4, ratings: 5, lat: 40.768669, lng: -73.913881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/chef-preparing-vegetable-dish-on-tree-slab-1267320.jpg"), filename: "6.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci1.jpg"), filename: "taci1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci2.jpg"), filename: "taci2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci3.jpg"), filename: "taci3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci4.jpg"), filename: "taci4.jpg")

Restaurant.create!(name: "Tava Turkish Mediterranean", phone_number: "(718) 499-5600", street_address: "318 5th Ave", city: "Brooklyn", state: "NY", zip: "11215", description: Faker::Restaurant.description, open_time: "11:00", close_time: "22:00", price_range: "$$$", capacity: 15, cuisines: "Turkish", owner_id: 2, ratings: 5, lat: 40.718669, lng: -73.915881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/clear-wine-glass-on-table-67468.jpg"), filename: "7.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma1.jpg"), filename: "shawarma1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma2.jpg"), filename: "shawarma2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma3.jpeg"), filename: "shawarma3.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma4.jpg"), filename: "shawarma4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/shawarma5.jpeg"), filename: "shawarma5.jpeg")

Restaurant.create!(name: "Ariana Afghan Kebab Restaurant", phone_number: "(212) 262-2323", street_address: "787 9th Ave", city: "Manhattan", state: "NY", zip: "10019", description: Faker::Restaurant.description, open_time: "11:30", close_time: "22:30", price_range: "$$", capacity: 15, cuisines: "Afgan", owner_id: 6, ratings: 5, lat: 40.763669, lng: -73.910881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/close-up-photo-of-formal-table-setting-735869.jpg"), filename: "8.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as1.jpg"), filename: "as1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as2.jpg"), filename: "as2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as3.jpg"), filename: "as3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as4.jpg"), filename: "as4.jpg")

Restaurant.create!(name: "The MasalaWala", phone_number: "(212) 358-9300", street_address: "179 Essex St", city: "Manhattan", state: "NY", zip: "10002", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$", capacity: 25, cuisines: "Indian", owner_id: 1, ratings: 5, lat: 40.730610, lng: -73.935242)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/empty-dining-tables-and-chairs-1579739.jpg"), filename: "9.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy3.jpg"), filename: "addy3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy4.jpg"), filename: "addy4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy5.jpg"), filename: "addy5.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy6.jpg"), filename: "addy6.jpg")

Restaurant.create!(name: "BURGERS by Honest Chops", phone_number: Faker::PhoneNumber.cell_phone, street_address: "99 MacDougal St", city: "Manhattan", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$", capacity: 25, cuisines: "Burgers & Wings", owner_id: 4, ratings: 5, lat: 40.712772, lng: -74.006058)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/empty-store-facade-with-lighted-fixtures-1449773.jpg"), filename: "10.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci1.jpg"), filename: "taci1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci2.jpg"), filename: "taci2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci3.jpg"), filename: "taci3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci4.jpg"), filename: "taci4.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Manhattan", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$$", capacity: 25, cuisines: "Burgers & Wings", owner_id: 4, ratings: 5, lat: 40.712712, lng: -74.006258)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/group-of-people-gathering-inside-bar-1058277.jpg"), filename: "11.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami1.jpg"), filename: "sami1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami2.jpeg"), filename: "sami2.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami3.jpg"), filename: "sami3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami4.jpg"), filename: "sami4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami5.jpg"), filename: "sami5.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Manhattan", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$", capacity: 25, cuisines: "Afgan", owner_id: 4, ratings: 5, lat: 40.712722, lng: -74.006458)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/inside-the-restaurant-with-pendant-lamps-and-flowers-704982.jpg"), filename: "12.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as1.jpg"), filename: "as1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as2.jpg"), filename: "as2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as3.jpg"), filename: "as3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as4.jpg"), filename: "as4.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Manhattan", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$", capacity: 25, cuisines: "Indian", owner_id: 4, ratings: 5, lat: 40.712732, lng: -74.00258)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/people-drinking-liquor-and-talking-on-dining-table-close-up-696218.jpg"), filename: "13.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan1.jpg"), filename: "duzan1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan2.jpg"), filename: "duzan2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan3.jpg"), filename: "duzan3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan4.jpg"), filename: "duzan4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/duzan5.png"), filename: "duzan5.png")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Manhattan", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$$", capacity: 25, cuisines: "Middle Eastern", owner_id: 4, ratings: 5, lat: 40.712772, lng: -74.006258)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/people-inside-room-and-surrounding-table-1581554.jpg"), filename: "14.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami1.jpg"), filename: "sami1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami2.jpeg"), filename: "sami2.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami3.jpg"), filename: "sami3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami4.jpg"), filename: "sami4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami5.jpg"), filename: "sami5.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Brooklyn", state: "NY", zip: "11223", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$", capacity: 25, cuisines: "Afgan", owner_id: 4, ratings: 5,lat: 40.761669, lng: -73.963881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/alcohol-architecture-bar-beer-260922.jpg"), filename: "15.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri1.jpeg"), filename: "peri1.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri2.jpg"), filename: "peri2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri3.jpg"), filename: "peri3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/peri4.jpg"), filename: "peri4.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Brooklyn", state: "NY", zip: "11223", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$", capacity: 25, cuisines: "Indian", owner_id: 4, ratings: 5, lat: 40.768669, lng: -73.917881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/photo-of-cafe-interior-1307698.jpg"), filename: "16.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci1.jpg"), filename: "taci1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci2.jpg"), filename: "taci2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci3.jpg"), filename: "taci3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci4.jpg"), filename: "taci4.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Brooklyn", state: "NY", zip: "11223", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$$", capacity: 25, cuisines: "Middle Eastern", owner_id: 4, ratings: 5, lat: 40.768669, lng: -73.963881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/restaurant-dark-bar-architecture-34650.jpg"), filename: "17.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as1.jpg"), filename: "as1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as2.jpg"), filename: "as2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as3.jpg"), filename: "as3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as4.jpg"), filename: "as4.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Brooklyn", state: "NY", zip: "11223", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$", capacity: 25, cuisines: "Afgan", owner_id: 4, ratings: 5, lat: 40.768669, lng: -73.9613881)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/restaurant-interior-776538.jpg"), filename: "18.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci1.jpg"), filename: "taci1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci2.jpg"), filename: "taci2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci3.jpg"), filename: "taci3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/taci4.jpg"), filename: "taci4.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Bronx", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$", capacity: 25, cuisines: "Indian", owner_id: 4, ratings: 5, lat: 40.837048, lng: -73.865433)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/selective-focus-photography-of-beef-steak-with-sauce-675951.jpg"), filename: "19.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy3.jpg"), filename: "addy3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy4.jpg"), filename: "addy4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy5.jpg"), filename: "addy5.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy6.jpg"), filename: "addy6.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Staten Island", state: "NY", zip: "10012", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$$", capacity: 25, cuisines: "Middle Eastern", owner_id: 4, ratings: 5, lat: 40.579021, lng: -74.151535)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/selective-focus-photography-of-open-signage-1036857.jpg"), filename: "20.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami1.jpg"), filename: "sami1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami2.jpeg"), filename: "sami2.jpeg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami3.jpg"), filename: "sami3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami4.jpg"), filename: "sami4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/sami5.jpg"), filename: "sami5.jpg")

Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Queens", state: "NY", zip: "12345", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$", capacity: 25, cuisines: "Seafood", owner_id: 1, ratings: 5, lat: 40.599021, lng: -74.351535)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/table-in-vintage-restaurant-6267.jpg"), filename: "21.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy3.jpg"), filename: "addy3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy4.jpg"), filename: "addy4.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy5.jpg"), filename: "addy5.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/addy6.jpg"), filename: "addy6.jpg")


Restaurant.create!(name: Faker::Restaurant.name, phone_number: Faker::PhoneNumber.cell_phone, street_address: Faker::Address.street_address, city: "Staten Island", state: "NY", zip: "78654", description: Faker::Restaurant.description, open_time: "12:00", close_time: "22:30", price_range: "$$$", capacity: 25, cuisines: "Vegetarian", owner_id: 4, ratings: 5, lat: 42.579021, lng: -75.151535)
# Restaurant.last.main_photo.attach(io: open("/home/vault/Desktop/halal-table-photos/profile-photos/white-and-brown-cooked-dish-on-white-ceramic-bowls-958545.jpg"), filename: "22.jpg")

# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as1.jpg"), filename: "as1.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as2.jpg"), filename: "as2.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as3.jpg"), filename: "as3.jpg")
# Restaurant.last.photos.attach(io: open("/home/vault/Desktop/halal-table-photos/as4.jpg"), filename: "as4.jpg")

Menu.create!(restaurant_id: 1, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 2, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 3, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 4, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 5, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 6, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 7, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 8, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 9, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 10, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 11, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 12, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 13, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 14, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 15, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 16, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 17, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 18, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 19, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 20, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 21, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 22, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")
Menu.create!(restaurant_id: 23, item_1: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_2: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_3: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_4: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_5: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}", item_6: "#{Faker::Food.dish}--> #{Faker::Food.description}-->$#{Faker::Commerce.price}")


Review.create!(restaurant_id: 1, user_id: 1, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 2, user_id: 1, overall: 3, food: 2, service: 5, ambience: 4, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 3, user_id: 1, overall: 3, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 4, user_id: 1, overall: 5, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 5, user_id: 1, overall: 4, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 6, user_id: 1, overall: 1, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 7, user_id: 1, overall: 5, food: 5, service: 4, ambience: 3, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 8, user_id: 1, overall: 3, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 9, user_id: 1, overall: 5, food: 2, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 1, user_id: 2, overall: 5, food: 4, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 2, user_id: 2, overall: 3, food: 5, service: 3, ambience: 3, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 3, user_id: 2, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 4, user_id: 2, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 5, user_id: 2, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 6, user_id: 2, overall: 2, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 7, user_id: 2, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 8, user_id: 2, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 9, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 1, user_id: 3, overall: 1, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 2, user_id: 3, overall: 3, food: 5, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 3, user_id: 3, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 4, user_id: 3, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 5, user_id: 3, overall: 5, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 6, user_id: 3, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 7, user_id: 3, overall: 5, food: 4, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 8, user_id: 3, overall: 4, food: 2, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 9, user_id: 3, overall: 2, food: 5, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 1, user_id: 4, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 2, user_id: 4, overall: 5, food: 2, service: 5, ambience: 4, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 3, user_id: 4, overall: 5, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 4, user_id: 4, overall: 5, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 5, user_id: 4, overall: 4, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 6, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 7, user_id: 4, overall: 5, food: 5, service: 4, ambience: 3, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 8, user_id: 4, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 9, user_id: 4, overall: 5, food: 2, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 1, user_id: 5, overall: 5, food: 4, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 2, user_id: 5, overall: 1, food: 5, service: 3, ambience: 3, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 3, user_id: 5, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 4, user_id: 5, overall: 5, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 5, user_id: 5, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 6, user_id: 6, overall: 5, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 7, user_id: 6, overall: 1, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 8, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 9, user_id: 6, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 1, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 2, user_id: 6, overall: 5, food: 5, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 3, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 4, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 5, user_id: 6, overall: 5, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 6, user_id: 7, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 7, user_id: 7, overall: 5, food: 4, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 8, user_id: 7, overall: 4, food: 2, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 9, user_id: 7, overall: 1, food: 5, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 10, user_id: 7, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 10, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 10, user_id: 5, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 11, user_id: 4, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 11, user_id: 7, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 11, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 11, user_id: 5, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 11, user_id: 1, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 12, user_id: 1, overall: 5, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 12, user_id: 2, overall: 5, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 12, user_id: 3, overall: 4, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 12, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 12, user_id: 5, overall: 5, food: 5, service: 4, ambience: 3, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 13, user_id: 6, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 13, user_id: 7, overall: 5, food: 2, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 14, user_id: 1, overall: 5, food: 2, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 14, user_id: 2, overall: 5, food: 4, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 15, user_id: 2, overall: 3, food: 5, service: 3, ambience: 3, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 16, user_id: 3, overall: 5, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 16, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 16, user_id: 5, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 16, user_id: 1, overall: 2, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 16, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 15, user_id: 3, overall: 1, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 17, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 17, user_id: 5, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 17, user_id: 1, overall: 2, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 17, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 18, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 21, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 18, user_id: 5, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 18, user_id: 1, overall: 2, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 18, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 19, user_id: 4, overall: 2, food: 2, service: 1, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 19, user_id: 5, overall: 2, food: 5, service: 5, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 20, user_id: 1, overall: 2, food: 5, service: 4, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 20, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 21, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 22, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 22, user_id: 1, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 23, user_id: 3, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )
Review.create!(restaurant_id: 23, user_id: 2, overall: 4, food: 5, service: 3, ambience: 5, body: Faker::Restaurant.review )

Favorite.create!(restaurant_id: 1, user_id: 2)
Favorite.create!(restaurant_id: 3, user_id: 2)
Favorite.create!(restaurant_id: 5, user_id: 2)
Favorite.create!(restaurant_id: 6, user_id: 2)
Favorite.create!(restaurant_id: 2, user_id: 1)
Favorite.create!(restaurant_id: 3, user_id: 1)
Favorite.create!(restaurant_id: 5, user_id: 1)
Favorite.create!(restaurant_id: 6, user_id: 1)
Favorite.create!(restaurant_id: 5, user_id: 3)
Favorite.create!(restaurant_id: 6, user_id: 3)
Favorite.create!(restaurant_id: 2, user_id: 3)
Favorite.create!(restaurant_id: 3, user_id: 3)
Favorite.create!(restaurant_id: 1, user_id: 4)
Favorite.create!(restaurant_id: 3, user_id: 4)
Favorite.create!(restaurant_id: 5, user_id: 4)
Favorite.create!(restaurant_id: 6, user_id: 4)
Favorite.create!(restaurant_id: 2, user_id: 5)
Favorite.create!(restaurant_id: 3, user_id: 5)
Favorite.create!(restaurant_id: 5, user_id: 5)
Favorite.create!(restaurant_id: 6, user_id: 5)
Favorite.create!(restaurant_id: 5, user_id: 6)
Favorite.create!(restaurant_id: 6, user_id: 6)
Favorite.create!(restaurant_id: 2, user_id: 6)
Favorite.create!(restaurant_id: 3, user_id: 6)


